### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [3]:
import numpy as np

# 1
primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])

# 2
#prende dal vettore primi quelli che sono primi > 10"
maggiori_10 = primi[primi > 10]

# 3
#prende dal vettore primi quelli che divisi per 2 danno resto 0"
pari = primi[primi % 2 == 0]

print("Numeri maggiori di 10:", maggiori_10)
print("Numeri pari:", pari)

Numeri maggiori di 10: [11 13 17 19]
Numeri pari: [2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [2]:
import numpy as np

# Generiamo un array da 1 a 15 e lo disponiamo su 5 righe e 3 colonne
a = np.arange(1, 16).reshape(5, 3)

### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [ ]:
import numpy as np
a = np.random.rand(10, 3) #array 10x3 con numeri casuali tra 0 e 1
distanza = np.abs(a - 0.5) #calcolo distanza di ogni elemento da 0.5
indici_colonna = np.argmin(distanza, axis = 1) #trova l'indice della colonna con il valore più vicino a 0.5 per ogni riga
indici_riga = np.arange(10) #array con indici da 0 a 9

risultato = a[indici_riga, indici_colonna]
print("Array originale:\n", a) 
print("Valori più vicini a 0.5 per riga:\n", risultato)

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------------------------------- -------- 9.7/12.3 MB 60.5 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 45.5 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.
Array originale:
 [[0.38425413 0.43724832 0.79982304]
 [0.25670003 0.04200714 0.56740261]
 [0.83223521 0.84656168 0.70384899]
 [0.15712962 0.86236086 0.79468621]
 [0.31384464 0.29838129 0.04069253]
 [0.73106725 0.40553148 0.03878544]
 [0.52694359 0.65939866 0.64004926]
 [0.20743469 0.8032569  0.75858706]
 [0.7273918  0.51760603 0.35923229]
 [0.13943186 0.12189966 0.15816618]]
Valori più vicini a 0.5 per riga:
 [0.43724832 0.56740261 0.70384899 0.79468621 0.31384464 0.40553148
 0.52694359 0.75858706 0.51760603 0.15816618]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [ ]:
import numpy as np
#1.
array = np.array([68, 65, 77, 110, 160, 161, 162, 161, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

#2.
min = np.min(array) 
print("Valore minimo:", min)

#3.
max =np.max(array) 
print("Valore massimo:", max)

#4.
arr = array > 120
print(arr) 

Valore minimo: 60
Valore massimo: 164
[False False False False  True  True  True  True  True  True  True  True
  True  True False False False False False False]


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [16]:
import numpy as np
#1 e 4
stipendi = np.array([50.000, 105.250, 55.000, 89.000], dtype = float)
costo_personale = sum(stipendi)
print("Costo totale del personale:", costo_personale)

#2.
stipendi[1] = stipendi[1] * 1.15
print(stipendi[1])

#5.
stipendi[0] = stipendi[0] * 1.20
print(stipendi[0])

#6.
stipendi[[2,3]] = stipendi[[2,3]] * 1.10
print(stipendi[2], stipendi[3])

#7.
costo_totale = sum(stipendi)
print("Costo totale dopo gli aumenti:", costo_totale)

Costo totale del personale: 299.25
121.0375
60.0
60.50000000000001 97.9
Costo totale dopo gli aumenti: 339.4375


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [ ]:
import numpy as np
# 1.
dati_co2 = np.loadtxt('emissioni.txt')

# 2. 
sopra_18 = dati_co2[dati_co2 > 18]
quantita = sopra_18.size
media = sopra_18.mean()

# 3. 
frazione = sopra_18.sum() / dati_co2.sum()

print("Valori sopra 18:", quantita)
print("Media dei valori sopra 18:", media)
print("Frazione sul totale:", frazione)

Valori sopra 18: 22
Media dei valori sopra 18: 19.09590909090909
Frazione sul totale: 0.1773439148972097


### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [20]:
import numpy as np

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

# 1. 
istruiti = survey_matrix[survey_matrix[:, 2] >= 12]

# 2.
redditi_istruiti = survey_matrix[survey_matrix[:, 2] >= 12, 1]

# 3.
reddito_medio = survey_matrix[survey_matrix[:, 2] >= 12, 1].mean()

print("Intervistati con istruzione >= 12:\n", istruiti)
print("Redditi selezionati:", redditi_istruiti)
print("Reddito medio:", reddito_medio)

Intervistati con istruzione >= 12:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
Redditi selezionati: [52000 63000 58000]
Reddito medio: 57666.666666666664


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [21]:
import numpy as np
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57,
                77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

# 1.
ages_clean = ages[ages != 999]

# 2.
max_age = ages_clean.max()

print(f"Numero di record errati rimossi: {ages.size - ages_clean.size}")
print(f"L'età del cittadino più anziano è: {max_age} anni.")

Numero di record errati rimossi: 13
L'età del cittadino più anziano è: 112 anni.


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [ ]:
import numpy as np
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

# 1.
estratte = np.random.choice(lista_parole, size=5, replace=True)

# 2.
storia = f"""
In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {estratte[0]} che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il {estratte[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "{estratte[2]}".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {estratte[3]}.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {estratte[4]}!" 
Ci fu grande gioia e celebrazione.
"""
print(storia)


In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico NEMICO che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il VERDURA come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "IMPERO".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BATTERIA.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza PALLONCINO!" 
Ci fu grande gioia e celebrazione.



Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."